Django 2
Niklas9/django-unixdatetimefield pull request #7
Opened 2019-02-07 10:26 UTC by kudlatyamroth

Avoid a RemovedInDjango30Warning in Django 2.0
And add tests in travis for Django 2.0, 2.1
Also provide matrix for travis config

2019-02-22 17:07 UTC, Niklas9 requested changes
Nice work, just one code improvement request to make things easier

2019-02-22 17:07 UTC, Niklas9 commented on django_unixdatetimefield/fields.py
> +            return self.to_python(val)
Since neither of the arguments following `val` is used, may I suggest that we do the following instead @kudlatyamroth 

```
def from_db_value(self, val, *args, **kwargs):
    return self.to_python(val)
```

2019-02-22 17:07 UTC, Niklas9 commented on django_unixdatetimefield/fields.py
> +            return self.to_python(val)
That way we don't add complexity with version handling, and it's 2 rows instead of 6 :)

2019-02-22 17:07 UTC, Niklas9 commented on django_unixdatetimefield/fields.py
> +import django
Not used?

2019-02-23 00:13 UTC, kudlatyamroth commented on django_unixdatetimefield/fields.py
> +            return self.to_python(val)
yep, you are right, thats best solution :)

2019-02-23 00:13 UTC, kudlatyamroth commented
changes commited :)
thansk for suggestions :)

2019-02-23 20:55 UTC, merged

2019-02-23 20:55 UTC, Niklas9 commented
Excellent @kudlatyamroth ! Thank you.
I'll have a new release out shortly